news_app/news_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news_portal.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),

]

news_app/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),
    path('upgrade/', upgrade_me, name='upgrade'),
]

news_app/news_portal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache


class Author(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.IntegerField(default=0)

    def __str__(self):
        return self.author.username

    def update_rating(self):
        all_post_rating = Post.objects.filter(author_id=self.pk).aggregate(post_rating=Sum('post_rating'))['post_rating'] * 3
        author_comment_rating = Comment.objects.filter(user_id=self.author).aggregate(comment_rating=Sum('comment_rating'))['comment_rating']
        post_comment_rating = Comment.objects.filter(post__author__author=self.author).aggregate(comment_rating=Sum('comment_rating'))['comment_rating']
        self.author_rating = all_post_rating + author_comment_rating + post_comment_rating
        self.save()
        return self.author_rating


class Category(models.Model):
    name_category = models.CharField(max_length=124, unique=True)
    subscribers = models.ManyToManyField(User, related_name='category')

    def get_subscribers(self):
        return self.subscribers

    def get_category(self):
        return self.name_category

    def __str__(self):
        return self.name_category


article = 'A'
news = 'N'
KIND = [
    (article, 'Article'),
    (news, 'News')
]


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_kind = models.CharField(max_length=1, choices=KIND, default=news)
    time_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    content = models.TextField()
    post_rating = models.IntegerField(default=0)

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        return f'{self.content[0:124]}...'

    def __str__(self):
        return f'{self.title}:{self.content[:20]} ({self.time_in})'

    def get_absolute_url(self):
        return reverse('news_one', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'news_one-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.category


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    time_in = models.DateTimeField(auto_now_add=True)
    comment_rating = models.IntegerField(default=0)

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()

    def __str__(self):
        return self.comment_text

news_app/templates/category.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
 {% if is_not_subscriber %}
   <p class="text-center"><a href="{% url 'subscribe' category.id %}" class = "btn btn-secondary btn-sm">Subscribe</a></p>
 {% else %}
    <p class="text-center"><a href="{% url 'unsubscribe' category.id %}" class = "btn btn-secondary btn-sm">Unsubscribe</a></p>
    {% endif %}
<h2>All posts</h2>
    <h3>{{ time_in|date:'d.m.Y' }}</h3>

   {% if category_news %}
       <table>
           <tr>
               <td>author</td>
               <td>title</td>
               <td>time_in</td>
               <td>content</td>
               <td>category</td>
           </tr>
           {% for post in category_news %}
           <tr>
               <td>{{ post.author|censor }}</td>
               <td>{{ post.title|censor }}</td>
               <td>{{ post.time_in|date:'d.m.Y' }}</td>
               <td>{{ post.content|truncatechars:20|censor }}</td>
               <td>
                   {% for category in post.category.all %}
                       {{ category }}
                   {% endfor %}
               </td>
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>No news published!</h2>
   {% endif %}

    {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

news_app/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Please find attached the new posts for the week!</h2>
<ul>
    {% for post in post %}
        <li><a> href="{{ link }}{{ post.get.absolute.erl }}{{ post.title }}"</a></li>
    {% endfor %}
</ul>
</body>
</html>

news_app/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

news_app/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h2>All posts</h2>
    <h3>{{ time_in|date:'d.m.Y' }}</h3>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   {% if news %}
       <table>
           <tr>
               <td>author</td>
               <td>title</td>
               <td>time_in</td>
               <td>content</td>
               <td>post_kind</td>
           </tr>
           {% for post in news %}
           <tr>
               <td>{{ post.author|censor }}</td>
               <td>{{ post.title|censor }}</td>
               <td>{{ post.time_in|date:'d.m.Y' }}</td>
               <td>{{ post.content|truncatechars:20|censor }}</td>
               <td>{{ post.get_post_kind_display }}</td>
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>No news published!</h2>
   {% endif %}

    {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

news_app/templates/news_one.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post
{% endblock title %}

{% block content %}
   <h1>Post</h1>
   <hr>
   {% if news_one %}
       <table>
           <tr>
               <td>author</td>
               <td>title</td>
               <td>time_in</td>
               <td>content</td>
           </tr>

           <tr>
               <td>{{ news_one.author }}</td>
               <td>{{ news_one.title }}</td>
               <td>{{ news_one.time_in|date:'d.m.Y' }}</td>
               <td>{{ news_one.content|truncatechars:20 }}</td>
           </tr>

       </table>
   {% else %}
       <h2>No news!</h2>
   {% endif %}
{% endblock content %}

news_app/templates/post.created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Please find attached the new post <a> href="{{ link}}"</a> in your favorite category.</h2>
        <p>{{ text }}</p>
</body>
</html>

news_app/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block title %}
Create news
{% endblock title %}

{% block content %}
<h1>News</h1>
<h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
</h2>
{% endblock content%}

news_app/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Post delete</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Delete "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

news_app/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block title %}
Post edit
{% endblock title %}

{% block content %}
<h1>Post</h1>
<h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Post edit"/>
    </form>
</h2>
{% endblock content%}

news_app/templates/search.html
{% extends 'flatpages/default.html' %}

{% block title %}
Search
{% endblock title %}

{% block content %}
    <h2>Search in posts</h2>
    <h3>{{ time_in|date:'d.m.Y' }}</h3>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Search"/>
    </form>
    {% for post in search %}
     <div>
     {{ post.author }}
     {{ post.title }}
     {{ post.time_in|date:'d.m.Y' }}
     {{ post.content|truncatechars:20 }}
     {{ post.get_post_kind_display }}
     </div>
    {% endfor %}
{% endblock content %}

news_app/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1> class="text-center">{{ message }}{{ category }}</h1>
{% endblock content %}

news_app/templates/welcome_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to the News_Portal </title>
</head>
<body>
   <h2>Welcome, {{ user.username }}</h2>
   <p> You have joined the News_Portal. Please enjoy our content.</p>
</body>
</html>